FROM python:3.11-slim

WORKDIR /app

# install deps first (better caching)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy app
COPY . .

# expose FastAPI port
EXPOSE 8000

# run app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]